doing task on the numpy matrix 

In [1]:
import numpy as np

mat1=np.array([[1 ,2],[5 ,7]])
mat1

array([[1, 2],
       [5, 7]])

In [2]:
mat2=np.array([[4,7],[8,6]])
mat2

array([[4, 7],
       [8, 6]])

In [3]:
multiply2mat = mat1 * mat2
multiply2mat

array([[ 4, 14],
       [40, 42]])

In [4]:
usedot=np.dot(mat1,mat2)
usedot

array([[20, 19],
       [76, 77]])

In [5]:
useadd=mat1 + mat2
useadd

array([[ 5,  9],
       [13, 13]])

In [6]:
matrixat=mat1@mat2 
matrixat

array([[20, 19],
       [76, 77]])

In [7]:
print(f"multiply :{multiply2mat} dotfunction : {usedot}")

multiply :[[ 4 14]
 [40 42]] dotfunction : [[20 19]
 [76 77]]
